apps/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


urlpatterns = [
    url(r'^$',views.home, name = "home"),
    url(r'login/', views.login_user, name = 'login'),
    url(r'^logout/$', views.logout_user, name= "logout"),

    #----------------------------------------------------------------------------
    url(r'^profile/$', views.edit_profile, name= "profile"),
    #---------------------------------------------------------------------------
    url(r'^register/$', views.register_user, name= "register"),
    
    url(r'^profile/$', views.edit_profile, name = "edit_profile"),
    
    
    # ****************************************************************
    # User Dashboard
    # ****************************************************************
    url(r'^dashbaord/$', views.dashboard, name = "dashboard"),
    
    #Password Change URL............
    url(r'^change_password/$', views.change_password, name = "change_password"),

    #password Reset URLS...........
    path('password_reset/', PasswordResetView.as_view(), name='password_reset' ),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    #Email Confirm URLs.....
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),

    #Contact Us Page ...
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^search/$', views.search, name="search"),
    ######### Plans ##################
    
    
    
    # ****************************************************************
    # Plan List that user creates
    # ****************************************************************
    url(r'^plan/$', views.Plans, name="plan"),



    url(r'^plandetail/(?P<id>\d+)/$', views.plandetail, name="plandetail"),
    
    
    # ****************************************************************
    # Plan Add Form
    # ****************************************************************
    url(r'^planform/$', views.planFormView, name="planform"),
    
    
    # ****************************************************************
    # Plan Edit Form
    # ****************************************************************
    url(r'^planeditform/(?P<id>\d+)/$', views.planEditFormView, name="planeditform"),
    
    # ****************************************************************
    # Plan Delete Form
    # ****************************************************************
    url(r'^delete/(?P<id>\d+)/$', views.delete_view,name='delete' ), 

    # ****************************************************************
    # Calculator Page
    # ****************************************************************
    path('calculator', views.CalculatorView, name="Calculator"),
    
    # ****************************************************************
    # Plan Join Page
    # ****************************************************************
    path('join-plan/<int:category_id>/<int:plan_id>/', views.Join_A_Plan, name="Join"),

    # ****************************************************************
    # Cancel a plan
    # ****************************************************************
    path('cancel-a-plan/<int:plan_id>', views.DeletePlan, name="DeletePlan"),
    
    # ****************************************************************
    # Cancel plan Request
    # ****************************************************************
    path("cancel-request/<int:cat_id>/<int:plan_id>", views.leaveFamily, name="leaveFamily" ),
    
    
    # ****************************************************************
    # Subscription Cancel Request
    # ****************************************************************
    path('cancel-subscription/<int:plan_id>/<int:sub_id>/', views.Cancel_A_Plan, name="cancel"),
    
    # ****************************************************************
    # Accept Subsription Cancel Request
    # ****************************************************************
    path('delete-subscription/<int:plan_id>/<int:sub_id>', views.Delete_Subscription, name="Delete"),
    
    # ****************************************************************
    # User plans
    # ****************************************************************
    path('user-plans', views.Plans, name="Plans"),
    
    # ****************************************************************
    # Approve a subscription for a user
    # ****************************************************************
    path('approve-subscription/<int:user_id>/<int:plan_id>/<int:sub_id>/', views.ApproveSubscription, name="Approve"),

    # ****************************************************************
    # Disapprove a subscription for a user
    # ****************************************************************
    path('disapprove-subscription/<int:user_id>/<int:plan_id>/<int:sub_id>/', views.DisapproveSubscription, name="Disapprove"),

    # ****************************************************************
    # Edit a subscription
    # ****************************************************************
    path("edit-a-subscription/<int:plan_id>/<int:sub_id>/", views.EditSubscription, name="EditSubscription"),
    
    # ****************************************************************
    # Subscription Detail View
    # ****************************************************************
    path('detail-view-subscription/<int:plan_id>/<int:sub_id>', views.Detail, name="Details"),

    # ****************************************************************
    # Device Campatibility
    # ****************************************************************
    path('confirm-reservation', views.deviceCompatibility, name="Reservation"),
    
    # ****************************************************************
    # About Us
    # ****************************************************************
    path('about-us', views.About, name="About"),
    
    # ****************************************************************
    # FAQ
    # ****************************************************************
    path('FAQ', views.FAQ, name="FAQ"),
    
    # ****************************************************************
    # Plan Comment View
    # ****************************************************************
    path('plan-comment/<int:plan_id>/', views.planCommentView, name="comment_plan"),
    
    # ********************************************************************
    
    # ****************************************************************
    # Payment Method Goes Here
    # ****************************************************************
    path('misc', views.misc, name="misc"),
    url(r'^edit_card/(?P<id>\w+)/$', views.edit_card, name="edit_card"),
    url(r'^delete_payment/(?P<id>\w+)/$', views.delete_payment, name="delete_payment"),
    url(r'^make_default/(?P<id>\w+)/$', views.make_default, name="make_default"),
    path('add_card', views.add_card, name="add_card"),
    path('list_card', views.list_card, name="list_card"),
    path('charge', views.charge, name="charge"),

    # ****************************************************************
    # Terms of use Page
    # ****************************************************************
    path("terms-of-use", views.TermsConditions, name="TermsConditions"),

    # ****************************************************************
    # Privacy Policy
    # ****************************************************************
    path("privacy-policy", views.PrivacyPolicy, name="PrivacyPolicy"),
    
   
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from apps.admin import my_admin_site


urlpatterns = [
    path('admin/', my_admin_site.urls),
    url(r'', include('apps.urls')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

apps/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.core.mail import EmailMessage
from django.dispatch import receiver
from django.contrib.auth.hashers import make_password
import datetime
from datetime import date
from django.core.exceptions import *


# ****************************************************************
# Subscription Choices
# ****************************************************************
SUBSCRIPTION_STATUS = (
    ("Inactive", "Joined"),
    ('Pending', "Pending Admin Approval"),
    ("Active", "Approve"),
    ("Ship", "Shipment"),
    ("Approved", "Activate"),

)

# ****************************************************************
# Plan Status
# ****************************************************************
PLAN_STATUS = (
    ("Inactive", "Joined"),
    ('Pending', "Pending Admin Approval"),
    ("Active", "Approve"),

)


FIXED_SLOT_CHOICES = [(int(i), str(i)) for i in range(1, 11)]


class profileModel(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    contactNumber = models.CharField(
        max_length=14, blank=True, null=True, default='')
    paid_untill = models.DateField(null=True, blank=True)
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

    class Meta:
        verbose_name = 'Profile'

    def get_contact(self):
        return self.contactNumber


class category(models.Model):
    Name = models.CharField(max_length=150)
    slug = models.CharField(max_length=150)
    def __str__(self):
        return self.Name

     # ****************************************************************
     # Get all plans for a specific category (Approved)
     # ****************************************************************
    def get_plans(self):
        return self.plan_set.all().filter(status="Active").order_by('total_slots')


# ****************************************************************
# Plan Names for a specific category
# ****************************************************************
class CategoryPlanName(models.Model):
    category = models.ForeignKey(category, on_delete= models.CASCADE)
    name = models.CharField(verbose_name="Plan Name", max_length = 100, default="", blank=False, null=True)
    
    def __str__(self):
        return f"{self.category}:{self.name}"


class plan(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    category = models.ForeignKey(category, on_delete=models.CASCADE)
    family_name = models.CharField(max_length=150)
    plan_name = models.CharField(max_length=150)
    number_of_open_slots = models.IntegerField(
        blank=False, default=0, null=False)
    monthly_payment_date = models.CharField(max_length=150)
    currently_monthly_payment_per_line = models.CharField(max_length=150)
    total_slots = models.IntegerField(
        verbose_name="Total Available Slots", blank=False, null=False, default=0, choices=FIXED_SLOT_CHOICES)
    linkWeb = models.URLField(
        max_length=200, blank=True, default='', null=True)
    currentFamilySize = models.IntegerField(verbose_name="Current Family Size",
                                            blank=True,
                                            null=True,
                                            default=0
                                            )
    notes = models.TextField(max_length=500, blank=True, default='', null=True)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=15, verbose_name="Plan Status",
                              default="Inactive", blank=False, null=False, choices=PLAN_STATUS)
    
    leaveRequest = models.BooleanField(verbose_name="Leave Request", default=False)

    def __str__(self):
        return self.plan_name

    # ****************************************************************
    # Get Category ID
    # ****************************************************************
    def get_category_id(self):
        return category.objects.get(id=self.category.id).id

    # ****************************************************************
    # Get Plan Owner Contact Number
    # ****************************************************************

    def get_contact(self):
        try:
            return profileModel.objects.get(user=User.objects.get(username=self.user.username)).contactNumber
        except:
            return None

    # ****************************************************************
    # Subscription Objects
    # ****************************************************************
    def get_subscription_objects(self):
        return self.subscription_set.all().order_by("-created_at")

    # ****************************************************************
    # Retrieve Plan Subscription status
    # ****************************************************************
    def get_approve_subscription(self):
        try:
            return subscription.objects.get(user=User.objects.get(username=self.user.username), plan__id=self.id)
        except:
            return None

    # ****************************************************************
    # Retrive whether the current plan have available slots to subscribe
    # ****************************************************************
    def get_available_status(self):
        return True

    # ****************************************************************
    # Retrive the Subscription model for current login user and plan
    # ****************************************************************
    def get_subscription(self):
        try:
            return subscription.objects.get(user=User.objects.get(username=self.user.username), plan__id=self.id)
        except:
            return None

    def get_comments(self):
        try:
            return self.commentplan_set.all().order_by("-timestamp")
        except:
            return None

    # ****************************************************************
    # Object Self Method
    # ****************************************************************
    def get_absolute_url(self):
        # return "join-plan/%i/%i/" % (self.category.id, self.id)
        return f"/plandetail/{self.id}/"


class subscription(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    plan = models.ForeignKey(plan, on_delete=models.CASCADE)
    number_of_slots = models.IntegerField(verbose_name="Number of Slots",
                                          blank=False,
                                          null=False,
                                          default=0)
    TotalAmount = models.IntegerField(verbose_name="Total Amount",
                                      blank=False,
                                      null=False,
                                      default=0)

    created_at = models.DateField(auto_now_add=True)

    feedback = models.TextField(
        verbose_name="Feedback", max_length=500, default="", blank=True, null=True)
    status = models.CharField(max_length=15, verbose_name="Subscription Status",
                              default="Inactive", blank=False, null=False, choices=SUBSCRIPTION_STATUS)
    leaveRequest = models.BooleanField(verbose_name="Leave Request", default=False)

    def __str__(self):
        return f"{self.user.username}'s Subscription"

# ****************************************************************
# Plan Member Comments
# ****************************************************************


class commentPlan(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    plan = models.ForeignKey(plan, on_delete=models.CASCADE)
    message = models.TextField(
        max_length=300, verbose_name="Commment Body", blank=False, default='', null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment By {self.user.username} on {self.plan.plan_name}"


class Api_key(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    paymentMenthod = models.CharField(max_length=150)
    customer_Id = models.CharField(max_length=150)
    subscription_ID = models.CharField(max_length=150)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username



    
class Payment_key(models.Model):
    user            = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    name           =models.CharField(max_length = 150)
    phone         =models.CharField(max_length = 150)
    email          =models.CharField(max_length = 150)
    last4           = models.CharField(max_length = 150)
    exp_month           = models.CharField(max_length = 150)
    exp_year           = models.CharField(max_length = 150)
    payment_id      = models.CharField(max_length = 150)
    default        =models.BooleanField(default='False',blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name
    class Meta:
        ordering= ['-timestamp','-updated']

apps/templates/music/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

{{ build_link }}{% url 'activate' uidb64=uid token=token %}{% if valuenext %}?next={{ valuenext }}{% endif %}
{% endautoescape %}

apps/templates/music/acc_active_email_confirm.html
{% extends "Base.html" %}
{% load static %}
{% block title %}Email Verification{% endblock %}







{% block register %}
<div class="register-login-area">
                            
        <a href="{% url 'register' %}" class="btn active">Register</a>
        <a href="{% url 'login' %}" class="btn">Login</a>
    
    </div>
{% endblock  %}




{% block content %}
  
    <div class="container" style="margin-top: 150px;">
      <div class="alert alert-info">
        <strong><h1>Email Verification</h1></strong><p>An email verification has been sent to "{{ email }}"</p>
      </div>
      
    </div>
{% endblock content %}

apps/templates/music/edit_profile.html
{% extends 'Base.html' %}
{% load static %}
{% load convert %}
{% block title %} Profile {% endblock %}
{% block content %}

<style>
    input::-webkit-inner-spin-button,
    input::-webkit-outer-spin-button {
        -webkit-appearance: none;
    }

    input[type="number"] {
        -moz-appearance: textfield;
    }
</style>

{% include "payment/add_method_modal.html" %}

<div class="col">


<div class="row mr-0">
    <div class="col-md-1">
        {% include 'music/side_bar.html' %}
    </div>

    <div class="col-md-6">
        <div class="mx-auto" style="width:400px;">
            <div class="card" style="width: 30rem;">
                <div class="card-header"> 
                    <h5 class="card-title mb-0 font-weight-bold">
                        Profile
                    </h5>
                    </div>

                <div class="card-body">
                    <form action="{% url 'edit_profile' %}" method="POST" id="registrationForm" class="needs-validation" novalidate>
                        {% csrf_token %}
                        {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-danger alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ message|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endif %}
                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% endif %}
                        {% if form_2.errors %}
                        {% for field in form_2 %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% for error in form_2.non_field_errors %}
                        <div class="alert alert-danger alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endif %}
                        <div class="form-group">
                            <label for="exampleUserName1">Username</label>
                            <input type="text" name="username" value="{{ request.user.username }}" maxlength="150"
                                required id="id_username" class="form-control">
                                <div class="invalid-feedback">
                                    Please provide a valid username.
                                  </div>
                            <small id="usernameHelpInline" class="text-muted">
                                Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
                            </small>
                        </div>
                        <div class="form-group">
                            <label for="exampleUserName1">Email</label>
                            <p type="text" class="card-text" >
                                {{ request.user.email }}
                                <br>
                                <small id="usernameHelpInline" class="text-muted">
                                    You can't edit email address.
                                </small>
                            </p>

                            
                        </div>

                        <div class="form-group">
                            <label for="exampleFirstName1">First Name</label>
                            <input type="text" name="first_name" value="{{ request.user.first_name }}" maxlength="30" required
                                id="id_first_name" class="form-control">
                                <div class="invalid-feedback">
                                    Please provide a valid First Name.
                                  </div>
                        </div>


                        <div class="form-group">
                            <label for="exampleLastName1">Last Name</label>
                            <input type="text" name="last_name" value="{{ request.user.last_name }}" maxlength="150" required
                                id="id_last_name" class="form-control">
                                <div class="invalid-feedback">
                                    Please provide a valid Last name.
                                  </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleLastName1">Contact Number</label>
                            <input type="text" name="contactNumber" value="{{ profile.contactNumber }}" maxlength="12" 
                                id="id_contactNumber" class="form-control" required>
                                <div class="invalid-feedback">
                                    Please provide a valid contact number.
                                  </div>
                            <small id="passwordHelpInline" class="text-muted">
                                Contact Number Format : 123-123-1234
                            </small>
                        </div>
                        <input type="hidden" name="password" value="{{ request.user.password }}" id="id_password">
                        <p class="text-right">
                            <a href="{% url 'edit_profile' %}" type="button" class="btn btn-danger"
                                value="Edit Profile">Cancel </a>
                            <button type="submit" class="btn btn-success" value="Edit Profile">Edit
                                
                                Profile</button>
                                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal">
                                    Add payment Method
                                  </button>
                                <div class="col-sm-12">
                                    <div class="row float-right">
                                        <a class="btn btn-info" href="{% url 'list_card' %}">List Payment Cards </a>
                                    </div>
                                </div>
                                
                                  
                        </p>
                    </form>



                </div>
            </div>
        </div>

    </div>
    <div class="col-lg-3">
        {% include "payment/misc.html" %}
    </div>
</div>
</div>
<script src="{% static 'music/js/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'music/js/contactNumberFormat_script.js' %}"></script>
<script src="{% static 'music/js/register_form_validation.js' %}"></script>
<script src="https://js.stripe.com/v3/"></script>
{% endblock content %}

apps/templates/music/home.html
{% extends 'Base.html' %}
{% load static humanize FindSubUser findNextYear findNextMonth %}
{{ form.media }}
{% block title %} Accounts {% endblock %}

{% block content %}


<link  rel="stylesheet" href="{% static 'music/css/homestylesheet.css' %}">
<script src="{% static 'music/js/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'music/js/calculator_slider.js' %}"></script>
<script src="{% static 'music/js/plan_creation_select_plan_name.js' %}"></script>
<script src="{% static 'music/js/monthly_payment_line_update.js' %}"></script>

{% if request.user.is_authenticated %}
  {% include 'music/home_add_plan_modal_form.html' %}
{% endif %}

  {% if not request.user.is_authenticated %}
    {% include 'music/login_register_modal.html' %}
  {% endif %}

<!-- ##### Hero Area Start ##### -->
<section class="hero-area bg-img bg-overlay-2by5"
  style="background-image: url( '{% static "music/bg-img/bg1.jpg" %}' );">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12">
        <!-- Hero Content -->
        <div class="hero-content text-center">

          {% if request.user.is_authenticated  %}
          <h2>Let's Manage Together</h2>
          {% else %}
          <h2>Let's Manage Together</h2>
          <a href="{% url 'login' %}" class="btn btn-primary .br-0">Get Started</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>
<!-- ##### Hero Area End ##### -->

{% include "music/calculator_section.html" %}
{% include "music/filter_section.html" %}





{%  if  categories %}

<div class="product">
  <div class="row ml-2 p-5 m-0">

    {% for i in categories  %}

    <p class="list-group-item mb-2 ml-4 font-weight-bold p-2 text-left border-0 pl-5 ml-5 mb-5 mt-5 col-lg-10"
      title="Category : {{ i.Name }}" style="max-width: 80% !important; font-size: 25px;">{{ i.Name }}</p>
    {% if request.user.is_authenticated %}
    <div class="col-md-4">
      <div class="card bg-info text-white font-weight-bold text-center pt-0 mb-2"
        style="width:300px !important; height: 300px !important; border-radius: 50% !important;">
        <div class="card-body mt-5 text-center">
          <h4 class="card-title text-white mb-5"></h4>
          <button href="{% url 'planform' %}" class="btn btn-secondary stretched-link" data-toggle="modal" onclick="PlanCreationFunction('{{ i.slug }}', '{{ i.id }}');"
            data-target="#exampleModal">Add a plan</button>
        </div>
      </div>
    </div>
    {% else %}
    <div class="col-md-4">
      <div class="card bg-transparent text-white font-weight-bold text-center pt-0 mb-2 border-0"
        style="width:300px !important; height: 300px !important; border-radius: 50% !important; box-shadow: none !important;">
        <div class="flip-card bg-transparent">
          <div class="flip-card-inner bg-transparent">
            <div class="flip-card-front bg-success text-white font-weight-bold text-center pt-0"
              style="width:300px !important; height: 300px !important; border-radius: 50% !important;">
              <div class="card-body mt-5 text-center text-secondary">
                <h4 class="card-title text-white mb-5"></h4>
                <button class="btn btn-secondary " data-toggle="modal" data-target="#exampleModal_1">Add a plan</button>
              </div>
            </div>
            <div class="flip-card-back bg-success text-white font-weight-bold text-center pt-0"
              style="width:300px !important; height: 300px !important; border-radius: 50% !important;">
              <div class="card-body mt-5 text-center text-secondary">
                <h4 class="card-title text-white mb-5"></h4>
                <button class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal_1">Login</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
    {% for j in i.get_plans %}
      {% include "music/home_plan_circle.html" with j=j %}
    {% endfor %}


    {% endfor %}

  </div>
</div>



{% endif %}


{% include "music/footer.html" %}


<script>
  $(document).ready(function(){
    $('#id_category').on("change", function()
    {
        if ($("#id_category :selected").text() == "VERIZON"){
              
          $("#id_plan_name_verizon").show();
          $("#id_plan_name_default").hide();
          $("#id_plan_name_t-mobiles").hide();
          $("#id_plan_name_AT-T").hide();

        }
        else if($("#id_category :selected").text() == "T-MOBILES"){
          $("#id_plan_name_verizon").hide();
          $("#id_plan_name_default").hide();
          $("#id_plan_name_t-mobiles").show();
          $("#id_plan_name_AT-T").hide();
        }
        else if($("#id_category :selected").text() == "AT-T"){
          $("#id_plan_name_verizon").hide();
          $("#id_plan_name_default").hide();
          $("#id_plan_name_t-mobiles").hide();
          $("#id_plan_name_AT-T").show();
        }
      
    });
  });
</script>


{% endblock content %}

apps/templates/music/index.html
<!doctype html>
<html>
    <head>
        <title>Responsive progress bar</title>
        <link href="css/main.css" rel="stylesheet" />
    </head>
    <body>

        <div class="progress-bar-wrapper"></div>

        <script src="js/progress-bar.js"></script>
        <script src="js/app.js"></script>
    </body>
</html>