apps/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


urlpatterns = [
    url(r'^$',views.home, name = "home"),
    url(r'login/', views.login_user, name = 'login'),
    url(r'^logout/$', views.logout_user, name= "logout"),

    #----------------------------------------------------------------------------
    url(r'^profile/$', views.edit_profile, name= "profile"),
    #---------------------------------------------------------------------------
    url(r'^register/$', views.register_user, name= "register"),
    
    url(r'^profile/$', views.edit_profile, name = "edit_profile"),
    
    
    # ****************************************************************
    # User Dashboard
    # ****************************************************************
    url(r'^dashbaord/$', views.dashboard, name = "dashboard"),
    
    #Password Change URL............
    url(r'^change_password/$', views.change_password, name = "change_password"),

    #password Reset URLS...........
    path('password_reset/', PasswordResetView.as_view(), name='password_reset' ),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    #Email Confirm URLs.....
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),

    #Contact Us Page ...
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^search/$', views.search, name="search"),
    ######### Plans ##################
    
    
    
    # ****************************************************************
    # Plan List that user creates
    # ****************************************************************
    url(r'^plan/$', views.Plans, name="plan"),



    url(r'^plandetail/(?P<id>\d+)/$', views.plandetail, name="plandetail"),
    
    
    # ****************************************************************
    # Plan Add Form
    # ****************************************************************
    url(r'^planform/$', views.planFormView, name="planform"),
    
    
    # ****************************************************************
    # Plan Edit Form
    # ****************************************************************
    url(r'^planeditform/(?P<id>\d+)/$', views.planEditFormView, name="planeditform"),
    
    # ****************************************************************
    # Plan Delete Form
    # ****************************************************************
    url(r'^delete/(?P<id>\d+)/$', views.delete_view,name='delete' ), 

    # ****************************************************************
    # Calculator Page
    # ****************************************************************
    path('calculator', views.CalculatorView, name="Calculator"),
    
    # ****************************************************************
    # Plan Join Page
    # ****************************************************************
    path('join-plan/<int:category_id>/<int:plan_id>/', views.Join_A_Plan, name="Join"),

    # ****************************************************************
    # Cancel a plan
    # ****************************************************************
    path('cancel-a-plan/<int:plan_id>', views.DeletePlan, name="DeletePlan"),
    
    # ****************************************************************
    # Cancel plan Request
    # ****************************************************************
    path("cancel-request/<int:cat_id>/<int:plan_id>", views.leaveFamily, name="leaveFamily" ),
    
    
    # ****************************************************************
    # Subscription Cancel Request
    # ****************************************************************
    path('cancel-subscription/<int:plan_id>/<int:sub_id>/', views.Cancel_A_Plan, name="cancel"),
    
    # ****************************************************************
    # Accept Subsription Cancel Request
    # ****************************************************************
    path('delete-subscription/<int:plan_id>/<int:sub_id>', views.Delete_Subscription, name="Delete"),
    
    # ****************************************************************
    # User plans
    # ****************************************************************
    path('user-plans', views.Plans, name="Plans"),
    
    # ****************************************************************
    # Approve a subscription for a user
    # ****************************************************************
    path('approve-subscription/<int:user_id>/<int:plan_id>/<int:sub_id>/', views.ApproveSubscription, name="Approve"),

    # ****************************************************************
    # Disapprove a subscription for a user
    # ****************************************************************
    path('disapprove-subscription/<int:user_id>/<int:plan_id>/<int:sub_id>/', views.DisapproveSubscription, name="Disapprove"),

    # ****************************************************************
    # Edit a subscription
    # ****************************************************************
    path("edit-a-subscription/<int:plan_id>/<int:sub_id>/", views.EditSubscription, name="EditSubscription"),
    
    # ****************************************************************
    # Subscription Detail View
    # ****************************************************************
    path('detail-view-subscription/<int:plan_id>/<int:sub_id>', views.Detail, name="Details"),

    # ****************************************************************
    # Device Campatibility
    # ****************************************************************
    path('confirm-reservation', views.deviceCompatibility, name="Reservation"),
    
    # ****************************************************************
    # About Us
    # ****************************************************************
    path('about-us', views.About, name="About"),
    
    # ****************************************************************
    # FAQ
    # ****************************************************************
    path('FAQ', views.FAQ, name="FAQ"),
    
    # ****************************************************************
    # Plan Comment View
    # ****************************************************************
    path('plan-comment/<int:plan_id>/', views.planCommentView, name="comment_plan"),
    
    # ********************************************************************
    
    # ****************************************************************
    # Payment Method Goes Here
    # ****************************************************************
    path('misc', views.misc, name="misc"),
    url(r'^edit_card/(?P<id>\w+)/$', views.edit_card, name="edit_card"),
    url(r'^delete_payment/(?P<id>\w+)/$', views.delete_payment, name="delete_payment"),
    url(r'^make_default/(?P<id>\w+)/$', views.make_default, name="make_default"),
    path('add_card', views.add_card, name="add_card"),
    path('list_card', views.list_card, name="list_card"),
    path('charge', views.charge, name="charge"),

    # ****************************************************************
    # Terms of use Page
    # ****************************************************************
    path("terms-of-use", views.TermsConditions, name="TermsConditions"),

    # ****************************************************************
    # Privacy Policy
    # ****************************************************************
    path("privacy-policy", views.PrivacyPolicy, name="PrivacyPolicy"),
    
   
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from apps.admin import my_admin_site


urlpatterns = [
    path('admin/', my_admin_site.urls),
    url(r'', include('apps.urls')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

apps/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.core.mail import EmailMessage
from django.dispatch import receiver
from django.contrib.auth.hashers import make_password
import datetime
from datetime import date
from django.core.exceptions import *


# ****************************************************************
# Subscription Choices
# ****************************************************************
SUBSCRIPTION_STATUS = (
    ("Inactive", "Joined"),
    ('Pending', "Pending Admin Approval"),
    ("Active", "Approve"),
    ("Ship", "Shipment"),
    ("Approved", "Activate"),

)

# ****************************************************************
# Plan Status
# ****************************************************************
PLAN_STATUS = (
    ("Inactive", "Joined"),
    ('Pending', "Pending Admin Approval"),
    ("Active", "Approve"),

)


FIXED_SLOT_CHOICES = [(int(i), str(i)) for i in range(1, 11)]


class profileModel(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    contactNumber = models.CharField(
        max_length=14, blank=True, null=True, default='')
    paid_untill = models.DateField(null=True, blank=True)
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

    class Meta:
        verbose_name = 'Profile'

    def get_contact(self):
        return self.contactNumber


class category(models.Model):
    Name = models.CharField(max_length=150)
    slug = models.CharField(max_length=150)
    def __str__(self):
        return self.Name

     # ****************************************************************
     # Get all plans for a specific category (Approved)
     # ****************************************************************
    def get_plans(self):
        return self.plan_set.all().filter(status="Active").order_by('total_slots')


# ****************************************************************
# Plan Names for a specific category
# ****************************************************************
class CategoryPlanName(models.Model):
    category = models.ForeignKey(category, on_delete= models.CASCADE)
    name = models.CharField(verbose_name="Plan Name", max_length = 100, default="", blank=False, null=True)
    
    def __str__(self):
        return f"{self.category}:{self.name}"


class plan(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    category = models.ForeignKey(category, on_delete=models.CASCADE)
    family_name = models.CharField(max_length=150)
    plan_name = models.CharField(max_length=150)
    number_of_open_slots = models.IntegerField(
        blank=False, default=0, null=False)
    monthly_payment_date = models.CharField(max_length=150)
    currently_monthly_payment_per_line = models.CharField(max_length=150)
    total_slots = models.IntegerField(
        verbose_name="Total Available Slots", blank=False, null=False, default=0, choices=FIXED_SLOT_CHOICES)
    linkWeb = models.URLField(
        max_length=200, blank=True, default='', null=True)
    currentFamilySize = models.IntegerField(verbose_name="Current Family Size",
                                            blank=True,
                                            null=True,
                                            default=0
                                            )
    notes = models.TextField(max_length=500, blank=True, default='', null=True)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=15, verbose_name="Plan Status",
                              default="Inactive", blank=False, null=False, choices=PLAN_STATUS)
    
    leaveRequest = models.BooleanField(verbose_name="Leave Request", default=False)

    def __str__(self):
        return self.plan_name

    # ****************************************************************
    # Get Category ID
    # ****************************************************************
    def get_category_id(self):
        return category.objects.get(id=self.category.id).id

    # ****************************************************************
    # Get Plan Owner Contact Number
    # ****************************************************************

    def get_contact(self):
        try:
            return profileModel.objects.get(user=User.objects.get(username=self.user.username)).contactNumber
        except:
            return None

    # ****************************************************************
    # Subscription Objects
    # ****************************************************************
    def get_subscription_objects(self):
        return self.subscription_set.all().order_by("-created_at")

    # ****************************************************************
    # Retrieve Plan Subscription status
    # ****************************************************************
    def get_approve_subscription(self):
        try:
            return subscription.objects.get(user=User.objects.get(username=self.user.username), plan__id=self.id)
        except:
            return None

    # ****************************************************************
    # Retrive whether the current plan have available slots to subscribe
    # ****************************************************************
    def get_available_status(self):
        return True

    # ****************************************************************
    # Retrive the Subscription model for current login user and plan
    # ****************************************************************
    def get_subscription(self):
        try:
            return subscription.objects.get(user=User.objects.get(username=self.user.username), plan__id=self.id)
        except:
            return None

    def get_comments(self):
        try:
            return self.commentplan_set.all().order_by("-timestamp")
        except:
            return None

    # ****************************************************************
    # Object Self Method
    # ****************************************************************
    def get_absolute_url(self):
        # return "join-plan/%i/%i/" % (self.category.id, self.id)
        return f"/plandetail/{self.id}/"


class subscription(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    plan = models.ForeignKey(plan, on_delete=models.CASCADE)
    number_of_slots = models.IntegerField(verbose_name="Number of Slots",
                                          blank=False,
                                          null=False,
                                          default=0)
    TotalAmount = models.IntegerField(verbose_name="Total Amount",
                                      blank=False,
                                      null=False,
                                      default=0)

    created_at = models.DateField(auto_now_add=True)

    feedback = models.TextField(
        verbose_name="Feedback", max_length=500, default="", blank=True, null=True)
    status = models.CharField(max_length=15, verbose_name="Subscription Status",
                              default="Inactive", blank=False, null=False, choices=SUBSCRIPTION_STATUS)
    leaveRequest = models.BooleanField(verbose_name="Leave Request", default=False)

    def __str__(self):
        return f"{self.user.username}'s Subscription"

# ****************************************************************
# Plan Member Comments
# ****************************************************************


class commentPlan(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    plan = models.ForeignKey(plan, on_delete=models.CASCADE)
    message = models.TextField(
        max_length=300, verbose_name="Commment Body", blank=False, default='', null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment By {self.user.username} on {self.plan.plan_name}"


class Api_key(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    paymentMenthod = models.CharField(max_length=150)
    customer_Id = models.CharField(max_length=150)
    subscription_ID = models.CharField(max_length=150)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username



    
class Payment_key(models.Model):
    user            = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    name           =models.CharField(max_length = 150)
    phone         =models.CharField(max_length = 150)
    email          =models.CharField(max_length = 150)
    last4           = models.CharField(max_length = 150)
    exp_month           = models.CharField(max_length = 150)
    exp_year           = models.CharField(max_length = 150)
    payment_id      = models.CharField(max_length = 150)
    default        =models.BooleanField(default='False',blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name
    class Meta:
        ordering= ['-timestamp','-updated']

apps/templates/app/Edit_Subscription_popup.html
{% load static %}


<script src="{% static 'music/js/jquery-2.2.4.min.js' %}"></script>

  <!-- Modal -->
  <div class="modal fade" id="exampleModalConfirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalConfirmLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalConfirmLabel">Confirmation</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            Are you sure you want to update your existing plan?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-success" onclick='$("#SubmitEditSubscriptionForm").submit();'>Save changes</button>
        </div>
      </div>
    </div>
  </div>

apps/templates/app/card.html
{% extends 'Base.html' %}
{% load static %}

{% block content %}


<script>
  card('{{STRIPE_PUBLISHABLE_KEY}}', '{{customer_email}}');
</script>

    <div class="row py-3">
        <div class="col-lg-12 col-md-12">
           <div class="container">
            <form action="{% url 'card' %}" method="post" id="payment-form">
              {% csrf_token %}
              <div id="card-element">
                <!-- Elements will create input elements here -->
              </div>
              <!-- We'll put the error messages in this element -->
              <div id="card-errors" role="alert"></div>
              <input type="hidden" name="payment_intent_id" value="{{ payment_intent_id }}" >
              <input type="hidden" name="stripe_plan_id" value="{{ stripe_plan_id }}" >
              <input type="hidden" name="automatic" value="{{ automatic }}" >

              <button id="submit-button">Pay</button>
            </form>
           </div>
        </div>
    </div>  
    
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'music/card.js' %}"></script>
{% endblock %}

apps/templates/app/delete_confirmation_for_plan.html
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModalPlanDelete_{{ plan.id }}_{{ plan.plan_name|slugify }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalPlanDelete_{{ plan.id }}_{{ plan.plan_name|slugify }}Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalPlanDelete_{{ plan.id }}_{{ plan.plan_name|slugify }}Label">Delete Confirmation</h5>
          
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            
          Are you sure you want to leave <span class="card-title font-weight-bold text-danger">{{ plan.plan_name }}</span>?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <a type="button" class="btn btn-success" href="{% url 'leaveFamily' plan.category.id plan.id  %}">Send cancel request</a>
        </div>
      </div>
    </div>
  </div>

apps/templates/app/delete_view.html
{% extends 'baseuser.html' %}
{% block content2 %}
<div class="container">
    
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
          There is error in  {{ field.name }} &nbsp;&nbsp;&nbsp; <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% endif %}
    <form method="POST">
        {% csrf_token %}
        
        <div class="card" style=" width: auto;">
                <div class="shadow p-3 bg-white rounded">

                    <div class="card-header text-center bg-transparent border-0">
                        <h3>
                                 
                              
                                     <form method="POST"> 
                                         {% csrf_token %} 
                                         Are you want to delete this plan ? 
                                         <input type="submit" class="btn btn-primary" value="Yes" /> 
                                         <a href="/" class="btn btn-primary">Cancel </a> 
                                     </form> 
                                 </div> 
                        </h3>

                    </div>
{% endblock %}

apps/templates/app/form_plan.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}



<script src="{% static 'music/js/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'music/js/plan_creation_select_plan_name.js' %}"></script>
<script src="{% static 'music/js/monthly_payment_line_update.js' %}"></script>






<div class="row mr-0">
    <div class="col">
        {% include 'music/side_bar.html' %}
    </div>
    <div class="col">
        <div class="mx-auto" style="width: 1000px;">


            <form method="POST">
                {% csrf_token %}

                <div class="card mb-5 mt-5" style=" width:45rem;">


                    <div class="shadow p-3 bg-white rounded">

                        <div class="card-header text-center bg-transparent border-0">
                            <h3>
                                Plan
                            </h3>

                        </div>
                        <div class="card-body">

                            {% if form.errors %}
                            {% for field in form %}
                            {% for error in field.errors %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                <h5 class="alert-heading">{{ field.label }}</h5>
                                <hr>
                                <p class="mb-0">{{ error|escape }}</p>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                            {% endfor %}
                            {% endif %}
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label>Category</label>

                                        {% if categories %}
                                        <select name="category" required="" id="id_category" class="form-control"
                                            onchange="updateLine();">
                                            <option value="False" disabled hidden selected>Select</option>
                                            {% for category in categories %}
                                            <option value="{{ category.id }}"
                                                onclick="PlanCreationFunction('{{ category.slug }}', '{{ category.id }}');">
                                                {{ category.slug|upper   }}</option>
                                            {% endfor %}

                                        </select>

                                    </div>

                                    <div class="form-group" id="selectContains">
                                        <label>Plan Name</label>

                                        <select class="form-control" name="plan_name" id="id_plan_name_default"
                                            style="display: block;">
                                            <option hidden>Select Category First</option>
                                        </select>
                                        {% for category in categories %}



                                        <select class="form-control" name="plan_name"
                                            id="id_plan_name_{{ category.slug }}" data-target="Verizon"
                                            style="display: none;">

                                            {% for j in category.categoryplanname_set.all %}
                                            <option value="{{ j.name }}">{{ j.name }}</option>
                                            {% endfor %}
                                        </select>



                                        {% endfor %}
                                        {% endif %}

                                    </div>


                                    <div class="form-group">
                                        <label>Family Name</label>
                                        <input type="text" name="family_name" maxlength="150" class="form-control"
                                            required=""
                                            {% if form.family_name.value %}value="{{ form.family_name.value }}"
                                            {% endif %}>
                                    </div>
                                </div>
                                <div class="col-md-2"></div>
                                <div class="col-md-5">

                                    <div class="form-group">
                                        <label>Total Available Slots</label>
                                        {{ form.total_slots }}

                                    </div>
                                    <div class="form-group">
                                        <label>Next Recurring Bill Date</label>
                                        <div class="input-group date" data-provide="datepicker" data-date-format="mm/dd/yyyy">
                                            <input type="text" name="monthly_payment_date" maxlength="150"
                                                class="form-control"
                                                {% if form.monthly_payment_date.value %}value="{{ form.monthly_payment_date.value }}"
                                                {% endif %} required="">
                                            <div class="input-group-addon">
                                                <span class="glyphicon glyphicon-th"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>How much are you currently paying per line?</label>
                                        <input type="number" name="currently_monthly_payment_per_line" maxlength="150"
                                            id="id_currently_monthly_payment_per_line"
                                            {% if form.currently_monthly_payment_per_line.value %}
                                            value="{{ form.currently_monthly_payment_per_line.value}}" {% endif %}
                                            class="form-control" required="" onkeyup="updateLine()">
                                    </div>
                                    <div class="form-group">
                                        <label class="text-danger card-text" id="currentLinePayment"
                                            style="display: none;"></label>
                                    </div>
                                    <div class="form-group">
                                        <label>Current Family Size</label>
                                        <input type="number" name="currentFamilySize" maxlength="3"
                                            {% if form.currentFamilySize.value %}
                                            value="{{ form.currentFamilySize.value}}" {% endif %} class="form-control"
                                            required="">
                                    </div>
                                </div>
                                <div class="col-md-12">

                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Additional Notes (Number of characters
                                            : <span id="CharactersCounter"></span>/500)</label>
                                        <textarea maxlength="500" class="form-control" id="exampleFormControlTextarea1"
                                            rows="3" onkeyup="countChar(this)"
                                            name="notes">{% if form.linkWeb.value %}{{ form.notes.value }}{% endif %}</textarea>
                                    </div>
                                </div>
                            </div>


                            <input type="submit" class="btn btn-primary mt-2" value="Save">

                            <a type="button" class="btn btn-danger mt-2" href="{% url 'planform' %}">Cancel</a>

                        </div>
                    </div>
                </div>





            </form>
        </div>

    </div>

</div>


{% endblock %}

apps/templates/app/misc.html
{% load convert %}
<h3>History</h3>
{%  for i in invoices%}
{{i.number}}<br>
{{i.amount_paid}}<br>
{{i.created | convert}}<br>
From:{{upcoming.period_start | convert}}<br>
To:{{upcoming.period_end | convert}}<br>
{% endfor %}
<h3>upcoming</h3>

{{upcoming.description}}<br>
{{upcoming.amount_due}}<br>
{{upcoming.created | convert }}<br>

{% for i in upcoming.lines.data %}
FROM:{{i.period.start | convert}}<br>
TO: {{i.period.end | convert}}<br>
{% endfor %}
<br>